excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData
  - TuLotero/External
  - LocalPackages/RLTMXProfiling.xcframework
  - LocalPackages/PayWithMyBank.xcframework
  - LocalPackages/PaymentSDK.xcframework
  - build

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition
  - type_body_length
  - block_based_kvo

custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))$'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: error

type_name:
  max_length:
    warning: 80

attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"
    - "@Test"
  severity: error

force_cast: error
force_try: warning
function_body_length:
    warning: 60

legacy_hashing: error

identifier_name:
  max_length:
    error: 40
  min_length:
    error: 3
  excluded:
    - i
    - id
    - x
    - y
    - z
    - dx
    - dy

line_length:
  warning: 120
  error: 120
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  severity: error
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
  
private_over_fileprivate:
  validate_extensions: true

trailing_whitespace:
  severity: error
  ignores_empty_lines: true
  ignores_comments: true
    
vertical_whitespace:
  max_empty_lines: 1
  severity: error

redundant_type_annotation:
  severity: error

opening_brace:
  severity: error

closing_brace:
  severity: error

nesting:
  type_level:
    error: 2
    warning: 2

indentation_width:
  severity: error
  include_compiler_directives: false
  include_comments: false

operator_usage_whitespace:
  severity: error

multiline_function_chains:
  severity: error

statement_position:
  severity: error
  
redundant_optional_initialization:
  severity: error

redundant_objc_attribute:
  severity: error

overridden_super_call:
  severity: error
  
superfluous_disable_command:
  severity: error

file_length:
  error: 401
  
colon:
  severity: error

operator_whitespace:
  severity: error

comma:
  severity: error

legacy_cggeometry_functions:
  severity: error

multiple_closures_with_trailing_closure:
  severity: error

cyclomatic_complexity:
  error: 10
  ignores_case_statements: true

trailing_semicolon:
  severity: error

trailing_comma:
  severity: error

multiline_parameters_brackets:
  severity: error
  
trailing_closure:
  severity: error

multiline_literal_brackets:
  severity: error

nsobject_prefer_isequal:
  severity: error

yoda_condition:
  severity: error

control_statement:
  severity: error

type_body_length:
  error: 250

array_init:
  severity: error
  
block_based_kvo:
  severity: error

function_parameter_count:
  error: 5

unneeded_override:
  severity: error

trailing_newline:
  severity: error

duplicate_imports:
  severity: error

xctfail_message:
  severity: error

unused_optional_binding:
  severity: error

vertical_whitespace_closing_braces:
  severity: error

return_arrow_whitespace:
  severity: error

comment_spacing:
  severity: error

vertical_whitespace_opening_braces:
  severity: error

class_delegate_protocol:
  severity: error

closure_spacing:
  severity: error

empty_enum_arguments:
  severity: error

redundant_discardable_let:
  severity: error

reduce_boolean:
  severity: error

unused_enumerated:
  severity: error
